### PR TITLE
[Docs] Fixed an issue with docker-compose configuration

### PR DESCRIPTION
**Pull request by HaotMan**
PR Related issue #1004

### CODE REVIEW

**Comment by HeChangHaoGary** [comment]
> 公关相关问题 [#1004 ](https://github.com/dingodb/dingo/issues/1004)
If you want to commit to develop branch, v0.7.0 should not be mentioned in Method one

**Comment by HaotMan** [comment]
> > 公关相关问题 [#1004 ](https://github.com/dingodb/dingo/issues/1004)
> > If you want to commit to develop branch, v0.7.0 should not be mentioned in Method one

I think I should replace it with the docker-compose.yml from the develop branch. So I added an additional commit to change v0.7.0 branch to develop branch in method1

**Comment by HeChangHaoGary** [comment]
> docker-compose.yml



> > > 公关相关问题 [#1004 ](https://github.com/dingodb/dingo/issues/1004)
> > > If you want to commit to develop branch, v0.7.0 should not be mentioned in Method one
> 
> I think I should replace it with the docker-compose.yml from the develop branch. So I added an additional commit to change v0.7.0 branch to develop branch in method1

There have been major changes to docker-compose.yml in the v0.7.0 branch and docker-compose.yml in the develop branch, and the web name has been changed to proxy.

**Comment by HaotMan** [comment]
> > docker-compose.yml
> 
> > > > 公关相关问题 [#1004 ](https://github.com/dingodb/dingo/issues/1004)
> > > > If you want to commit to develop branch, v0.7.0 should not be mentioned in Method one
> > 
> > 
> > I think I should replace it with the docker-compose.yml from the develop branch. So I added an additional commit to change v0.7.0 branch to develop branch in method1
> 
> There have been major changes to docker-compose.yml in the v0.7.0 branch and docker-compose.yml in the develop branch, and the web name has been changed to proxy.

Does this mean that the documentation about ‘Deploy In Single Node Using Docker’ needs to be rewritten? Or simply modify the dingo-store/docker/docker-compose.yml, adding configurations for the executor and web?

**Comment by HeChangHaoGary** [comment]
> > > docker-compose.yml
> > 
> > 
> > > > > 公关相关问题 [#1004 ](https://github.com/dingodb/dingo/issues/1004)
> > > > > If you want to commit to develop branch, v0.7.0 should not be mentioned in Method one
> > > 
> > > 
> > > I think I should replace it with the docker-compose.yml from the develop branch. So I added an additional commit to change v0.7.0 branch to develop branch in method1
> > 
> > 
> > There have been major changes to docker-compose.yml in the v0.7.0 branch and docker-compose.yml in the develop branch, and the web name has been changed to proxy.
> 
> Does this mean that the documentation about ‘Deploy In Single Node Using Docker’ needs to be rewritten? Or simply modify the dingo-store/docker/docker-compose.yml, adding configurations for the executor and web?
The web process in the develop branch has been canceled in docker. You can modify the web uniformly to proxy. If you need to modify the v0.7.0 branch, you can pr to v0.7.0 separately.

**Comment by HeChangHaoGary** [comment]
> > > docker-compose.yml
> > 
> > 
> > > > > 公关相关问题 [#1004 ](https://github.com/dingodb/dingo/issues/1004)
> > > > > If you want to commit to develop branch, v0.7.0 should not be mentioned in Method one
> > > 
> > > 
> > > I think I should replace it with the docker-compose.yml from the develop branch. So I added an additional commit to change v0.7.0 branch to develop branch in method1
> > 
> > 
> > There have been major changes to docker-compose.yml in the v0.7.0 branch and docker-compose.yml in the develop branch, and the web name has been changed to proxy.
> 
> Does this mean that the documentation about ‘Deploy In Single Node Using Docker’ needs to be rewritten? Or simply modify the dingo-store/docker/docker-compose.yml, adding configurations for the executor and web?

The web process in the develop branch has been canceled in docker. You can modify the web uniformly to proxy. If you need to modify the v0.7.0 branch, you can pr to v0.7.0 separately.

**Comment by HaotMan** [comment]
> > > > docker-compose.yml
> > > 
> > > 
> > > > > > 公关相关问题 [#1004 ](https://github.com/dingodb/dingo/issues/1004)
> > > > > > If you want to commit to develop branch, v0.7.0 should not be mentioned in Method one
> > > > 
> > > > 
> > > > I think I should replace it with the docker-compose.yml from the develop branch. So I added an additional commit to change v0.7.0 branch to develop branch in method1
> > > 
> > > 
> > > There have been major changes to docker-compose.yml in the v0.7.0 branch and docker-compose.yml in the develop branch, and the web name has been changed to proxy.
> > 
> > 
> > Does this mean that the documentation about ‘Deploy In Single Node Using Docker’ needs to be rewritten? Or simply modify the dingo-store/docker/docker-compose.yml, adding configurations for the executor and web?
> 
> The web process in the develop branch has been canceled in docker. You can modify the web uniformly to proxy. If you need to modify the v0.7.0 branch, you can pr to v0.7.0 separately.

Okay, thank you very much for your answer. Now I have replaced 'web' with 'proxy' in the documentation of develop branch, and I also submitted a PR for the documentation of v0.7.0 branch.

**Review by astor-oss — APPROVED** [review]

**Pull request merged**
